---
- name: Prune Docker System
  hosts: all

  tasks:
    - name: Prune Docker system
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
        builder_cache: true

