---
- name: Init Docker Swarm
  hosts: manager
  become: true

  vars:
    secure_nw_cidr: "10.2.0.0/24"
    secure_nw_gateway: "10.2.0.1"
    dns_nw_cidr: "10.3.0.0/24"
    dns_nw_gateway: "10.3.0.1"
    mtu: 1280

  tasks:
    - name: Run tailscale ip --4 command
      ansible.builtin.command: tailscale ip --4
      register: tailscale_ip_output

    - name: Store Tailscale IPv4 Address in a variable
      ansible.builtin.set_fact:
        tailscale_ip: "{{ tailscale_ip_output.stdout }}"

    - name: Print the Tailscale IPv4 Address
      ansible.builtin.debug:
        msg: "The Tailscale IPv4 Address is: {{ tailscale_ip }}"

    - name: Initialize Docker Swarm using Tailscale IP
      community.docker.docker_swarm:
        state: present
        advertise_addr: "{{ tailscale_ip }}"
        data_path_addr: "{{ tailscale_ip }}"
        force_new_cluster: true

    - name: Remove existing Docker networks if any
      community.docker.docker_network:
        name: "{{ item }}"
        state: absent
      loop:
        - ingress
        - secure
        - db
        - external
      ignore_errors: true

    - name: Create custom ingress network
      community.docker.docker_network:
        name: ingress
        driver: overlay
        driver_options:
          com.docker.network.driver.mtu: "{{ mtu }}"
        scope: swarm
        internal: false

    - name: Create custom secure network
      community.docker.docker_network:
        name: secure
        driver: overlay
        driver_options:
          com.docker.network.driver.mtu: "{{ mtu }}"
        ipam_config:
          - subnet: "{{ secure_nw_cidr }}"
            gateway: "{{ secure_nw_gateway }}"
        attachable: true

    - name: Create custom db network
      community.docker.docker_network:
        name: db
        driver: overlay
        driver_options:
          com.docker.network.driver.mtu: "{{ mtu }}"
        attachable: true

    - name: Create custom dns network
      community.docker.docker_network:
        name: dns
        driver: overlay
        driver_options:
          com.docker.network.driver.mtu: "{{ mtu }}"
        ipam_config:
          - subnet: "{{ dns_nw_cidr }}"
            gateway: "{{ dns_nw_gateway }}"
        attachable: true

    - name: Create custom external network
      community.docker.docker_network:
        name: external
        driver: overlay
        driver_options:
          com.docker.network.driver.mtu: "{{ mtu }}"
        attachable: true
