- name: Install Docker
  hosts: all
  become: true

  tasks:
    - name: Download Docker convenience script
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh

    - name: Run Docker convenience script
      command: sh /tmp/get-docker.sh

    - name: Add current user to the Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Restart Docker service
      service:
        name: docker
        state: restarted

    - name: Write /etc/docker/daemon.json
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "default-network-opts": {
              "bridge": {
                "com.docker.network.driver.mtu": "1280"
              },
              "overlay": {
                "com.docker.network.driver.mtu": "1280"
              }
            }
          }

    - name: Restart Docker service
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: Remove docker_gwbridge network if it exists
      shell: docker network rm docker_gwbridge

    - name: Create docker_gwbridge network with specified options
      shell: >
        docker network create --driver bridge
        --opt com.docker.network.driver.mtu=1280
        --opt com.docker.network.bridge.enable_ip_masquerade=true
        --opt com.docker.network.bridge.name=docker_gwbridge
        docker_gwbridge
