- name: Install Docker
  hosts: all
  become: true

  tasks:
    - name: Download Docker convenience script
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh

    - name: Run Docker convenience script
      command: sh /tmp/get-docker.sh

    - name: Add current user to the Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Update daemon.json
      import_role:
        name: json_modifier
      vars:
        json_file_path: /etc/docker/daemon.json
        modifier: add
        additional_content:
          default-network-opts:
            bridge:
              com.docker.network.driver.mtu: "1280"
            overlay:
              com.docker.network.driver.mtu: "1280"

    - name: Restart Docker service
      ansible.builtin.service:
        name: docker
        state: restarted

    - name: Remove docker_gwbridge network if it exists
      command: docker network rm docker_gwbridge
      ignore_errors: yes
      register: result

    - name: Check if network removal was successful or network did not exist
      assert:
        that:
          - result.rc == 0 or 'network docker_gwbridge not found' in result.stderr
        fail_msg: "Failed to remove docker_gwbridge network for reasons other than it not existing."

    - name: Create docker_gwbridge network with specified options
      shell: >
        docker network create --driver bridge
        --opt com.docker.network.driver.mtu=1280
        --opt com.docker.network.bridge.enable_ip_masquerade=true
        --opt com.docker.network.bridge.name=docker_gwbridge
        docker_gwbridge
