---
- name: Configure Time Synchronization
  hosts: all
  become: true
  tasks:
    - name: Install systemd-timesyncd or chrony
      ansible.builtin.package:
        name: "{{ 'systemd-timesyncd' if ansible_facts.os_family == 'Debian' else 'chrony' }}"
        state: present

    - name: Enable and start time synchronization service
      ansible.builtin.systemd:
        name: "{{ 'systemd-timesyncd' if ansible_facts.os_family == 'Debian' else 'chrony' }}"
        enabled: true
        state: started
