---
- name: Join Docker swarm
  hosts: agents
  become: true

  vars_prompt:
    - name: swarm_token
      prompt: "Enter Docker swarm worker join token"
      private: true

    - name: swam_manager_ip
      prompt: "Enter Docker swarm manager IP"
      private: false

  tasks:
    - name: Validate swarm join parameters
      ansible.builtin.assert:
        that:
          - swarm_token | length > 0
          - swam_manager_ip | length > 0
        fail_msg: "Swarm token and manager IP must be provided"

    - name: Install UFW
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - name: Allow TCP traffic on port 2377 from 100.64.0.0/10 on tailscale0
      ansible.builtin.command: ufw allow in on tailscale0 from 100.64.0.0/10 proto tcp to any port 2377
      register: ufw_result
      changed_when: "'Skipping' not in ufw_result.stdout and 'Skipping' not in ufw_result.stderr"

    - name: Allow TCP traffic on port 7946 from 100.64.0.0/10 on tailscale0
      ansible.builtin.command: ufw allow in on tailscale0 from 100.64.0.0/10 to any port 7946
      register: ufw_result
      changed_when: "'Skipping' not in ufw_result.stdout and 'Skipping' not in ufw_result.stderr"

    - name: Allow UDP traffic on port 4789 from 100.64.0.0/10 on tailscale0
      ansible.builtin.command: ufw allow in on tailscale0 from 100.64.0.0/10 proto udp to any port 4789
      register: ufw_result
      changed_when: "'Skipping' not in ufw_result.stdout and 'Skipping' not in ufw_result.stderr"

    - name: Allow TCP traffic on port 2377 from fd7a:115c:a1e0:ab12::/64 on tailscale0
      ansible.builtin.command: ufw allow in on tailscale0 from fd7a:115c:a1e0:ab12::/64 proto tcp to any port 2377
      register: ufw_result
      changed_when: "'Skipping' not in ufw_result.stdout and 'Skipping' not in ufw_result.stderr"

    - name: Allow TCP traffic on port 7946 from fd7a:115c:a1e0:ab12::/64 on tailscale0
      ansible.builtin.command: ufw allow in on tailscale0 from fd7a:115c:a1e0:ab12::/64 to any port 7946
      register: ufw_result
      changed_when: "'Skipping' not in ufw_result.stdout and 'Skipping' not in ufw_result.stderr"

    - name: Allow UDP traffic on port 4789 from fd7a:115c:a1e0:ab12::/64 on tailscale0
      ansible.builtin.command: ufw allow in on tailscale0 from fd7a:115c:a1e0:ab12::/64 proto udp to any port 4789
      register: ufw_result
      changed_when: "'Skipping' not in ufw_result.stdout and 'Skipping' not in ufw_result.stderr"

    - name: Allow all inbound traffic on tailscale0
      community.general.ufw:
        rule: allow
        interface: tailscale0
        direction: in

    - name: Reload UFW
      community.general.ufw:
        state: reloaded

    - name: Join Swarm as Worker
      ansible.builtin.command: "docker swarm join --token {{ swarm_token }} {{ swam_manager_ip }}:2377"
