---
- name: Set Asia/Kolkata timezone
  hosts: all
  become: true
  tasks:
    - name: Ping test
      ping:
      
    - name: Set timezone to Asia/Kolkata
      timezone:
        name: Asia/Kolkata
