---
- name: Configure UFW and Allow OpenSSH
  hosts: all
  become: true

  tasks:
    - name: Install UFW
      apt:
        name: ufw
        state: present

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Allow OpenSSH
      ufw:
        rule: allow
        name: OpenSSH

    - name: Allow all traffic on tailscale0 (inbound)
      ufw:
        rule: allow
        interface: tailscale0
        direction: in

    - name: Allow all traffic on tailscale0 (outbound)
      ufw:
        rule: allow
        interface: tailscale0
        direction: out

    - name: Reload UFW
      ufw:
        state: reloaded
