version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:30"
    target-branch: "master"
    assignees:
      - "hibare"
    groups:
      actions:
        patterns:
          - "*"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/ansible"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:30"
    target-branch: "master"
    assignees:
      - "hibare"
    groups:
      python:
        patterns:
          - "*"

  # Maintain dependencies for terraform modules
  - package-ecosystem: "terraform"
    directory: "/terraform/cloudflare"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "00:30"
    target-branch: "master"
    assignees:
      - "hibare"
    groups:
      terraform:
        patterns:
          - "*"