version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "00:30"
    target-branch: "master"
    assignees:
      - "hibare"
    groups:
      actions:
        patterns:
          - "*"

  # Maintain dependencies for Python
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "00:30"
    target-branch: "master"
    assignees:
      - "hibare"
    groups:
      python:
        patterns:
          - "*"

  # Maintain dependencies for terraform modules
  - package-ecosystem: "terraform"
    directory: "/terraform/cloudflare"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "00:30"
    target-branch: "master"
    assignees:
      - "hibare"
    groups:
      terraform:
        patterns:
          - "*"

  # Maintain dependencies for pre-commit
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "00:30"
    target-branch: "master"
    assignees:
      - "hibare"
    groups:
      pre-commit:
        patterns:
          - "*"
