# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 05fd71a57a467ccf5598f7e836d3af4cf9225abb # v1.108.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate

  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        language_version: python3
        types: [python]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff
        args: [--fix]
        types_or: [python, pyi]

  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'docker run --rm -v "$(pwd):/workdir" -i --rm trufflesecurity/trufflehog:latest git file:///workdir --since-commit HEAD --results=verified,unknown --fail'
        language: system
        stages: ["commit", "push"]
        exclude: (.*/node_modules/|.*venv/|etc/|dist/)
      - id: tflint
        name: TFLint (Docker)
        description: Linter for Terraform config.
        entry: docker run --rm -v "./:/data" ghcr.io/terraform-linters/tflint:v0.53.0 --recursive
        language: system
        files: \.tf$
        pass_filenames: false

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
